package com.piyush.DiamondHotel.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.time.LocalDate;

@Data
@Entity   // JPA entity, meaning it's a data model that will be mapped to a database table.
@Table(name = "bookings")    // field data of Entity should Map to database table "bookings"
public class Booking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // id should be auto-generated by the database.
    private Long id;

    @NotNull(message = "check in date is required")
    private LocalDate checkInDate;

    @Future(message = "check out date must be in the future")
    private LocalDate checkOutDate;

    @Min(value = 1, message = "Number of adults must not be less than 1")
    private int numOfAdults;

    @Min(value = 0, message = "Number of children must not be less than 0")
    private int numOfChildren;

    private int totalNumOfGuest;

    private String bookingConfirmationCode;

    // One User can have many bookings.
    @ManyToOne(fetch = FetchType.EAGER)   // Fetch :- to get entry quickly / slowly .
    @JoinColumn(name = "user_id")
    private User user;

    // One Room can have many bookings on diff-diff dates
    @ManyToOne(fetch = FetchType.LAZY)    // Fetch :- to get entry quickly / slowly .
    @JoinColumn(name = "room_id")
    private Room room;


    public void calculateTotalNumberOfGuest() {
        this.totalNumOfGuest = this.numOfAdults + this.numOfChildren;
    }

    public void setNumOfAdults(int numOfAdults) {
        this.numOfAdults = numOfAdults;
        calculateTotalNumberOfGuest();
    }

    public void setNumOfChildren(int numOfChildren) {
        this.numOfChildren = numOfChildren;
        calculateTotalNumberOfGuest();
    }

    @Override
    public String toString() {
        return "Booking{" +
                "id=" + id +
                ", checkInDate=" + checkInDate +
                ", checkOutDate=" + checkOutDate +
                ", numOfAdults=" + numOfAdults +
                ", numOfChildren=" + numOfChildren +
                ", totalNumOfGuest=" + totalNumOfGuest +
                ", bookingConfirmationCode='" + bookingConfirmationCode + '\'' +
                '}';
    }
}
