package com.piyush.DiamondHotel.entity;
import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity     // JPA entity, meaning it's a data model that will be mapped to a database table.
@Table(name = "rooms")  // field data of Entity should map to database table "rooms"
public class Room {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   // id should be auto-generated by the database.
    private Long id;

    private String roomType;
    private BigDecimal roomPrice;
    private String roomPhotoUrl;
    private String roomDescription;

    @OneToMany(mappedBy = "room", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Booking> bookings = new ArrayList<>();
/*
Established a one-to-many relationship with the Booking entity, meaning
one room can have multiple bookings on different days.
&   the related bookings should be loaded lazily
*/

    @Override
    public String toString() {
        return "Room{" +
                "id=" + id +
                ", roomType='" + roomType + '\'' +
                ", roomPrice=" + roomPrice +
                ", roomPhotoUrl='" + roomPhotoUrl + '\'' +
                ", roomDescription='" + roomDescription + '\'' +
                '}';
    }
}
